{% set reqfile = "requirements.txt" %}
{% set name = "unionml" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unionml-{{ version }}.tar.gz
  sha256: f755f85f1ef71b61c895ada99cc2cdb010cf9d045c7facfa4d4cedb5fd02c300

build:
  number: 1
  noarch: python
  entry_points:
    - unionml = unionml.cli:app
  script:
    ## Ensure inclusion of requirements.txt
    {% set reqfile = "requirements.txt" %}
    {% set reqsource = name ~ ".egg-info/requires.txt" %}
    # IF {{ reqfile }} is NOT PRESENT, COPY {{ reqfile }} from {{ reqsource }}
    - echo -e "\n>>> ENSURE INCLUSION OF '{{ reqfile }}' <<<\n\n"
    - if [ ! -f {{ reqfile }} ] && [ -f {{ reqsource }} ]; then cp {{ reqsource }} {{ reqfile }}; fi  # [not win]
    #- copy {{ name }}.egg-info\requires.txt {{ reqfile }}  # [win]
    - copy {{ reqsource | replace('/', '\\') }} {{ reqfile }}  # [win] 
    ## Install package {{ name }} from PyPI 
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - click
    - cookiecutter
    - dataclasses-json
    - docker-py
    - fastapi
    - flytekit >=1.0.0
    - gitpython
    - joblib
    - mangum
    - numpy
    - pandas
    - pydantic
    - scikit-learn
    - typer
    - uvicorn
    # necessary for gitpython
    - git

test:
  imports:
    - unionml
  commands:
    #- pip check
    - unionml --help
  requires:
    - pip

about:
  home: https://pypi.org/project/unionml/
  summary: The easiest way to build and deploy machine learning microservices.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    **UnionML** is an open source MLOps framework that aims to reduce the boilerplate and friction
    that comes with building models and deploying them to production.

    You can create **UnionML Apps** by defining a few core methods that are automatically bundled
    into ML microservices, starting with model training and offline and online prediction.

    Built on top of [Flyte](https://docs.flyte.org/en/latest/), UnionML provides a high-level
    interface for productionizing your ML models so that you can focus on curating a better dataset
    and improving your models.

    To learn more, check out the 📖 [documentation](https://unionml.readthedocs.io).

    PyPI: [https://pypi.org/project/unionml/](https://pypi.org/project/unionml/)

  doc_url: https://unionml.readthedocs.io/
  dev_url: https://github.com/unionai-oss/unionml

extra:
  recipe-maintainers:
    - sugatoray
